import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowDown } from "lucide-react";
import { PROJECTS, getProject } from "@/lib/projects";
import { getService } from "@/lib/services";
import { L, UI } from "@/lib/l10n";
import { ORG_ID, JsonLd, breadcrumbJsonLd, pageMetadata } from "@/lib/seo";
import { absoluteUrl } from "@/lib/site";
import {
  CaseShots,
  ClosingCta,
  ContentSection,
  LivePreview,
  PageHero,
  ProjectLinkCard,
  Summary,
  T,
} from "@/components/page-kit";

type Props = { params: Promise<{ slug: string }> };

export function generateStaticParams() {
  return PROJECTS.map((p) => ({ slug: p.slug }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const p = getProject(slug);
  if (!p) return {};
  return pageMetadata({
    title: p.seoTitle,
    description: p.seoDescription,
    path: `/realisations/${p.slug}`,
    // Project card generated by opengraph-image.tsx next to this file.
    image: `/realisations/${p.slug}/opengraph-image`,
  });
}

export default async function CaseStudyPage({ params }: Props) {
  const { slug } = await params;
  const p = getProject(slug);
  if (!p) notFound();

  const service = getService(p.serviceSlug);
  const others = PROJECTS.filter((x) => x.slug !== p.slug).slice(0, 2);
  const url = absoluteUrl(`/realisations/${p.slug}`);
  const jsonLang = p.siteLanguage.fr === "Français" ? "fr" : p.siteLanguage.fr === "Turc" ? "tr" : "en";

  const facts = [
    { label: UI.factActivity, value: <T l={p.sector} /> },
    {
      label: UI.factPlace,
      value: (
        <>
          {p.city}, <T l={p.country} />
        </>
      ),
    },
    { label: UI.factLang, value: <T l={p.siteLanguage} /> },
    { label: UI.factRole, value: <T l={p.role} /> },
    {
      label: UI.factServices,
      value: (
        <>
          {p.services.map((s, i) => (
            <span key={s.fr}>
              {i > 0 && ", "}
              <T l={s} />
            </span>
          ))}
        </>
      ),
    },
  ];

  return (
    <div>
      <JsonLd
        data={[
          breadcrumbJsonLd([
            { name: "Accueil", path: "/" },
            { name: "Réalisations", path: "/realisations" },
            { name: p.name, path: `/realisations/${p.slug}` },
          ]),
          {
            "@context": "https://schema.org",
            "@type": "CreativeWork",
            "@id": `${url}#project`,
            name: `Site web de ${p.name}`,
            description: p.summary.fr,
            url,
            image: absoluteUrl(p.shots.desktop.src),
            creator: { "@id": ORG_ID },
            about: `${p.sector.fr}, ${p.city}`,
            inLanguage: jsonLang,
          },
        ]}
      />

      <PageHero
        crumbs={[{ name: UI.home, href: "/" }, { name: UI.work, href: "/realisations" }, { name: p.name }]}
        kicker={L(
          `${p.sector.fr} · ${p.city}`,
          `${p.sector.en} · ${p.city}`,
          `${p.sector.tr} · ${p.city}`,
        )}
        title={p.h1}
        lead={p.summary}
      >
        <div className="mt-8 flex flex-wrap gap-3">
          <a
            href="#apercu"
            className="inline-flex items-center gap-2 rounded-full bg-accent px-7 py-3.5 text-sm font-semibold whitespace-nowrap text-accent-foreground transition-transform duration-200 hover:scale-[1.03] active:scale-[0.98]"
          >
            <T l={UI.viewLive} /> <ArrowDown size={16} aria-hidden />
          </a>
        </div>
      </PageHero>

      <CaseShots project={p} />

      <Summary>{p.context}</Summary>

      <ContentSection title={UI.brief}>
        <dl className="grid grid-cols-1 gap-x-10 gap-y-6 sm:grid-cols-2">
          {facts.map((f) => (
            <div key={f.label.fr} className="border-t border-border pt-4">
              <dt className="text-xs tracking-widest text-muted-foreground uppercase">
                <T l={f.label} />
              </dt>
              <dd className="mt-1.5 text-foreground">{f.value}</dd>
            </div>
          ))}
        </dl>
      </ContentSection>

      <ContentSection id="apercu" title={UI.previewTitle}>
        <LivePreview concept={p} real />
      </ContentSection>

      <ContentSection title={UI.design}>
        <p className="max-w-2xl leading-relaxed text-muted-foreground">
          <T l={p.design} />
        </p>
      </ContentSection>

      <ContentSection title={UI.features}>
        <ul className="max-w-2xl space-y-3">
          {p.features.map((f) => (
            <li key={f.fr} className="flex gap-3 text-foreground/90">
              <span aria-hidden className="mt-2.5 h-px w-4 shrink-0 bg-accent" />
              <span>
                <T l={f} />
              </span>
            </li>
          ))}
        </ul>
        {service && (
          <p className="mt-10 text-sm text-muted-foreground">
            <T l={UI.sameType} />{" "}
            <Link href={`/services/${service.slug}`} className="text-accent underline-offset-4 hover:underline">
              <T l={UI.seeOffer} /> <T l={service.name} />
            </Link>
            .
          </p>
        )}
      </ContentSection>

      <ContentSection title={UI.others} world="world-navy">
        <div className="grid grid-cols-1 gap-6 md:grid-cols-2">
          {others.map((o) => (
            <ProjectLinkCard key={o.slug} project={o} />
          ))}
        </div>
      </ContentSection>

      <ClosingCta title={UI.caseClosingTitle} text={UI.caseClosingText} />
    </div>
  );
}
